function pars = getParams()
% Use a hashtable or dictionary data structure. 
    params_name = {'V_tr','Km_tr','n','k_pr','kdeg_m','k_tl', ...
                   'kdeg_p','k_sec', 'pr_fold_mko','pr_fold_tko','tl_fold', 'sec_fold',...
                  'Km_tr_fold'};
    %    params_value = [1,   0.5,     3, 0.6  , 0.02,   0.06,  ...
    %               0.06*10, 0.06,   1.5, 1.5, 5];
    params_value = [1,   0.65,     2, 0.4  , 0.02,   0.05,  ...
                   log(2)/10, log(2)/10,   4.2, 1.5,1.5, 5,...
                    2];
    
    pars = containers.Map(params_name,params_value);
end